# Redirect all requests to /index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Build settings
[build]
command = "npm run build"
publish = "build"

# Functions settings
[functions]
node_bundler = "esbuild"
node_version = "20.x"
